# Generated by Django 3.1.1 on 2021-01-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('template', models.ImageField(upload_to='templates/', verbose_name='Plantilla')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Foto')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('toptext', models.CharField(blank=True, max_length=200, verbose_name='Texto Superior')),
                ('bottomtext', models.CharField(blank=True, max_length=200, verbose_name='Texto Superior')),
                ('othertext', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto adicional')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
    ]
